export const SPECIALIZATIONS = [
    { id: '1', name: 'Cardiology' },
    { id: '2', name: 'Dermatology' },
    { id: '3', name: 'Neurology' },
    { id: '4', name: 'Pediatrics' },
    { id: '5', name: 'Psychiatry' },
    { id: '6', name: 'Orthopedics' },
    { id: '7', name: 'Gynecology' },
    { id: '8', name: 'Oncology' },
    { id: '9', name: 'Urology' },
    { id: '10', name: 'Gastroenterology' },
    { id: '11', name: 'Nephrology' },
    { id: '12', name: 'Ophthalmology' },
    { id: '13', name: 'Pulmonology' },
    { id: '14', name: 'Endocrinology' },
    { id: '15', name: 'Hematology' },
    { id: '16', name: 'Rheumatology' },
    { id: '17', name: 'Plastic Surgery' },
    { id: '18', name: 'General Surgery' },
    { id: '19', name: 'Anesthesiology' },
    { id: '20', name: 'Emergency Medicine' },
    { id: '21', name: 'Radiology' },
    { id: '22', name: 'Pathology' },
    { id: '23', name: 'Infectious Diseases' },
    { id: '24', name: 'Family Medicine' },
    { id: '25', name: 'Internal Medicine' },
    { id: '26', name: 'Geriatrics' },
    { id: '27', name: 'Allergy and Immunology' },
    { id: '28', name: 'Sports Medicine' },
    { id: '29', name: 'Dermatopathology' },
    { id: '30', name: 'Vascular Surgery' }
  ];
  